"""
Write build/installer.nsh: the NSIS lines that install the Gujarati fonts.

    python3 scripts/installer-fonts.py

The installer puts every font in build/fonts/ into Windows, for the user who
installs the app, so Excel, Word and every other program on the PC can print
the reports' fonts too - not only the app, which carries its own copies.

The font's name in the registry is read from the font file itself, so the two
can never disagree. Needs fontTools (pip install fonttools); run it again after
adding or replacing a font.
"""
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "build" / "fonts"
OUT = ROOT / "build" / "installer.nsh"

lines = []
for path in sorted(FONTS.glob("*.ttf")):
    name = TTFont(path)["name"].getDebugName(4)  # the full name: "Noto Sans Gujarati Bold"
    lines.append(f'  !insertmacro SmcInstallFont "{path.name}" "{name}"')

OUT.write_text(
    """; SMC Accounts - installs the Gujarati fonts the reports use.
; GENERATED by scripts/installer-fonts.py from build/fonts/ - edit that, not this.
;
; Fonts go to the installing user's own font folder (Windows 10 1809 and
; later), registered under HKCU, so no administrator rights are needed - the
; app itself installs per user too. A font already there is left as it is: it
; may be open in Excel, and replacing a font in use fails. Uninstalling the
; app leaves the fonts, because documents made with them still need them.

!define SMC_FONT_DIR "$LOCALAPPDATA\\Microsoft\\Windows\\Fonts"
!define SMC_FONT_KEY "Software\\Microsoft\\Windows NT\\CurrentVersion\\Fonts"

!macro SmcInstallFont FILE NAME
  SetOutPath "${SMC_FONT_DIR}"
  SetOverwrite off
  File "${BUILD_RESOURCES_DIR}\\fonts\\${FILE}"
  SetOverwrite on
  WriteRegStr HKCU "${SMC_FONT_KEY}" "${NAME} (TrueType)" "${SMC_FONT_DIR}\\${FILE}"
  ; Make it usable at once, without logging off.
  System::Call 'gdi32::AddFontResource(t "${SMC_FONT_DIR}\\${FILE}") i .s'
  Pop $0
!macroend

!macro customInstall
  DetailPrint "Installing the Gujarati fonts..."
  CreateDirectory "${SMC_FONT_DIR}"
"""
    + "\n".join(lines)
    + """
  ; Tell programs already running that new fonts are here.
  SendMessage ${HWND_BROADCAST} ${WM_FONTCHANGE} 0 0 /TIMEOUT=5000
  ; Back where the app's own files go.
  SetOutPath "$INSTDIR"
!macroend
""",
    encoding="utf-8",
)
print(f"{OUT.relative_to(ROOT)}: {len(lines)} fonts")
